export interface Bed {
	id?: number;
	name?: string;
	age?: number;
	sex?: string;
	floorNumber?: string;
	bedNo?: string;
	ipAddress?: string;
	wardNo?: string;
	bedId?: string;
	time?: string;
	tempCurrent?: number;
	tempAvg?: number;
	bpmCurrent?: number;
	bpmAvg?: number;
	bpDiastolicAvg: number,
	bpDiastolicCurrent: number,
	bpSystolicAvg: number,
	bpSystolicCurrent: number,
	systolicBPMaxima: number,
	diastolicBPMaxima: number,
	heartRateMaxima: number,
	heartRateMinima: number,
	heartRateCurrent: number,
	heartRateAvg: number,
	spO2Current?: number;
	spO2Avg?: number;
	spO2Minima?: number;
	status?: number;
}
